# Generated by Django 5.2.1 on 2025-07-01 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='content',
            field=models.TextField(help_text='문의 내용을 자세히 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='문의글 작성일(자동 입력)'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(default='접수', help_text='문의 처리 상태를 입력하세요. (예: 접수, 완료, 대기 등)', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(help_text='문의글의 제목을 입력하세요.', max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(help_text='문의글을 작성한 회원을 선택하세요. (회원 탈퇴시 문의글도 삭제됨)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inquiryreply',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='답변을 작성한 관리자 계정(선택사항, 삭제시에도 답변 보존).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inquiryreply',
            name='content',
            field=models.TextField(help_text='답변 내용을 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='inquiryreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='답변 작성일(자동 입력)'),
        ),
        migrations.AlterField(
            model_name='inquiryreply',
            name='inquiry',
            field=models.ForeignKey(help_text='어떤 문의글에 대한 답변인지 선택하세요.', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='inquiry.inquiry'),
        ),
    ]
