# Generated by Django 5.2.1 on 2025-07-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_content_alter_inquiry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('waiting', '접수'), ('answered', '답변완료'), ('closed', '종료')], default='waiting', help_text='문의 처리 상태 (접수, 답변완료, 종료 등 중 선택)', max_length=20),
        ),
    ]
