# Generated by Django 5.2.1 on 2025-07-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_alter_inquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('waiting', '접수'), ('answered', '답변완료')], default='waiting', help_text='문의 처리 상태 (접수, 답변완료 중 선택)', max_length=20),
        ),
    ]
