# Generated by Django 5.2.1 on 2025-07-01 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_alter_inquiry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(help_text='문의글을 작성한 회원을 선택하세요. (회원 탈퇴시에도 문의글 보존됨)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
