# Generated by Django 5.2.1 on 2025-07-01 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_alter_festivalimage_image'),
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, help_text='위시리스트에 등록된 날짜(자동 입력)'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='festival',
            field=models.ForeignKey(help_text='관심을 등록한 축제를 선택하세요. (축제 삭제 시 함께 삭제)', on_delete=django.db.models.deletion.CASCADE, to='festivals.festival'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='notify',
            field=models.BooleanField(default=True, help_text='축제 일정 알림 여부 (ON: 알림, OFF: 알림 없음)'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(help_text='이 위시리스트를 등록한 회원입니다. (회원 탈퇴 시 삭제)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
