# Generated by Django 5.2.1 on 2025-07-01 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_alter_festival_contact_phone_and_more'),
        ('shortforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortform',
            name='caption',
        ),
        migrations.AlterField(
            model_name='shortform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='쇼츠 등록일 (자동 생성)'),
        ),
        migrations.AlterField(
            model_name='shortform',
            name='festival',
            field=models.ForeignKey(blank=True, help_text="이 쇼츠가 관련된 축제를 선택하세요. (삭제시에도 쇼츠는 남고 [템플릿/뷰 등에서 null => '없어진 축제입니다' 전환 로직 작성 필요])", null=True, on_delete=django.db.models.deletion.SET_NULL, to='festivals.festival'),
        ),
        migrations.AlterField(
            model_name='shortform',
            name='title',
            field=models.CharField(help_text='쇼츠의 제목을 입력하세요. (필수)', max_length=100),
        ),
        migrations.AlterField(
            model_name='shortform',
            name='user',
            field=models.ForeignKey(blank=True, help_text="쇼츠를 작성한 회원을 선택하세요. (탈퇴시에도 쇼츠는 남고 [템플릿/뷰 등에서 null => '탈퇴한 사용자' 전환 로직 작성 필요])", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shortformimage',
            name='image',
            field=models.ImageField(help_text='업로드할 이미지 파일을 선택하세요. (최소 1장, 최대 6장)', upload_to='shortforms/images/'),
        ),
        migrations.AlterField(
            model_name='shortformimage',
            name='shortform',
            field=models.ForeignKey(help_text='이미지가 첨부될 쇼츠를 선택하세요.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shortforms.shortform'),
        ),
        migrations.AlterField(
            model_name='shortformimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='이미지 업로드 일시 (자동 생성)'),
        ),
    ]
