# Generated by Django 5.2.1 on 2025-07-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortforms', '0002_remove_shortform_caption_alter_shortform_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortform',
            name='title',
            field=models.CharField(help_text='쇼츠의 제목을 입력하세요. (필수)', max_length=50),
        ),
    ]
