# Generated by Django 5.2.1 on 2025-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortforms', '0003_alter_shortform_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortform',
            name='frame_color',
            field=models.CharField(default='default', help_text="프레임 색상(예: 'red', '#FF5733', 'default' 등)", max_length=20),
        ),
    ]
