# Generated by Django 5.2.1 on 2025-07-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='admin', help_text='서비스 내 닉네임(중복 불가, 필수).', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='Junhyoung', help_text='사용자의 실제 이름(본명, 필수).', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='회원 가입일(자동 생성).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='로그인에 사용하는 이메일 주소(중복 불가).', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_tags',
            field=models.ManyToManyField(blank=True, help_text='회원이 관심 있는 태그(여러 개 선택 가능).', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='비활성화하면 로그인 및 서비스 이용 불가.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='관리자 권한 여부. 체크하면 관리자페이지 접근 가능.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('local', '일반가입'), ('kakao', '카카오'), ('naver', '네이버')], default='local', help_text='계정 생성 방식(local, kakao, naver 등) 중 택1.', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='연락 가능한 전화번호 (선택사항).', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, help_text='카카오/네이버 등 소셜 로그인 회원의 고유 ID(일반회원은 비워둠).', max_length=100, null=True),
        ),
    ]
