# Generated by Django 5.2.1 on 2025-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest_tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
