# Generated by Django 5.2.1 on 2025-06-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_interest_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interest_tags',
        ),
    ]
