# Generated by Django 5.2.1 on 2025-07-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username_user_nickname_user_real_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='temp', help_text='로그인에 사용하는 아이디(중복 불가, 필수).', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='본인 확인용 이메일 주소(중복 불가, 필수).', max_length=254, unique=True),
        ),
    ]
