# Generated by Django 5.2.1 on 2025-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_interest_tags'),
        ('tags', '0003_remove_tag_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest_tags',
            field=models.ManyToManyField(blank=True, to='tags.tag'),
        ),
    ]
