# Generated by Django 5.2.1 on 2025-07-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_user_id_alter_user_email'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='회원 가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='로그인/알림용 이메일 주소 (중복 불가)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest_tags',
            field=models.ManyToManyField(blank=True, help_text='관심 태그', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='계정 활성화 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='관리자 권한 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('local', '일반가입'), ('kakao', 'kakao'), ('naver', 'naver')], default='local', help_text='계정 생성 방식 (local, kakao, naver 등)', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', help_text='닉네임(중복 불가, 필수)', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='연락처(선택)', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(help_text='사용자 본명(필수)', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, help_text='소셜로그인 회원 고유ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(help_text='서비스 내 회원 아이디. (소셜회원은 자동생성)', max_length=30, unique=True),
        ),
    ]
