# Generated by Django 5.2.1 on 2025-07-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('user_id', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('real_name', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=32)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.CharField(blank=True, max_length=16, null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
