# Generated by Django 5.2.1 on 2025-06-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_interest_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('local', '일반가입'), ('kakao', '카카오'), ('naver', '네이버')], default='local', help_text='계정 생성 방식을 구분 (local, kakao, naver 등)', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, help_text='카카오/네이버 등 소셜 회원 고유 ID', max_length=100, null=True),
        ),
    ]
