# Generated by Django 5.2.4 on 2025-07-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_gender'),
        ('tags', '0003_remove_tag_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest_tags',
            field=models.ManyToManyField(blank=True, help_text='관심 태그', related_name='user_set', to='tags.tag'),
        ),
    ]
