# Generated by Django 5.2.1 on 2025-07-01 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_alter_festivalimage_image'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, help_text='이미지 파일을 업로드하세요.', null=True, upload_to='reviews/images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='댓글 내용을 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='댓글 작성일 (자동 입력)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(help_text='댓글을 작성할 후기를 선택하세요.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='댓글 수정일 (자동 입력)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='댓글을 작성한 회원입니다. (회원 탈퇴 시 댓글도 삭제)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(help_text='후기 본문을 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='후기 작성일 (자동 입력)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='festival',
            field=models.ForeignKey(help_text='후기를 작성할 축제를 선택하세요. (축제 삭제 시 후기 같이 삭제)', on_delete=django.db.models.deletion.CASCADE, to='festivals.festival'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='축제 평점(1~5점 중 선택, 기본값 5점)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='후기 수정일 (자동 입력)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='후기를 작성한 회원입니다. (회원 탈퇴 시 후기 삭제)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='이미지 업로드 일시 (자동 입력)'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(help_text='이미지를 첨부할 후기를 선택하세요.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review'),
        ),
    ]
