# Generated by Django 5.2.1 on 2025-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
