# Generated by Django 5.2.1 on 2025-06-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_user_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user_count',
        ),
    ]
