# Generated by Django 5.2.1 on 2025-07-01 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('region', models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('JEJU', '제주'), ('INCHEON', '인천'), ('GWANGJU', '광주'), ('Daegu', '대구'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기도'), ('Chungcheongbuk', '충청북도'), ('Chungcheongnam', '충청남도'), ('jeonnam', '전라남도'), ('Gyeongsangbuk', '경상북도'), ('Gyeongsangnam', '경상남도'), ('Gangwon', '강원도'), ('jeonbuk', '전북')], default='SEOUL', max_length=20)),
                ('detail_region', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('fee', models.PositiveIntegerField(default=0)),
                ('organizer', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=12)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('JEJU', '제주'), ('INCHEON', '인천'), ('GWANGJU', '광주'), ('Daegu', '대구'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기도'), ('Chungcheongbuk', '충청북도'), ('Chungcheongnam', '충청남도'), ('jeonnam', '전라남도'), ('Gyeongsangbuk', '경상북도'), ('Gyeongsangnam', '경상남도'), ('Gangwon', '강원도'), ('jeonbuk', '전북')], max_length=20, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FestivalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='festivals/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='festivals.festival')),
            ],
        ),
    ]
