# Generated by Django 5.2.1 on 2025-07-01 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='문의 전화번호를 숫자만 입력하세요. (예: 0212345678, 선택사항)', max_length=12),
        ),
        migrations.AlterField(
            model_name='festival',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='데이터가 등록된 일시(자동 입력).'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='description',
            field=models.TextField(help_text='축제 상세 설명을 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='detail_region',
            field=models.CharField(help_text='축제가 개최되는 상세 주소를 입력하세요.', max_length=100),
        ),
        migrations.AlterField(
            model_name='festival',
            name='end_date',
            field=models.DateField(help_text='축제 종료 날짜를 선택하세요. (예: 2025-05-12)'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='fee',
            field=models.PositiveIntegerField(default=0, help_text='참가 요금을 원 단위로 입력하세요. (무료이면 0 입력)'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='축제 위치의 위도를 입력하세요. (예: 37.5665357)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='축제 위치의 경도를 입력하세요. (예: 126.9779692)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(help_text='축제 공식 명칭을 입력하세요. (예: 서울불꽃축제)', max_length=100),
        ),
        migrations.AlterField(
            model_name='festival',
            name='organizer',
            field=models.CharField(blank=True, help_text='축제 주최 기관 또는 부서를 입력하세요. (선택사항)', max_length=100),
        ),
        migrations.AlterField(
            model_name='festival',
            name='region',
            field=models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('JEJU', '제주'), ('INCHEON', '인천'), ('GWANGJU', '광주'), ('Daegu', '대구'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기도'), ('Chungbuk', '충북'), ('Chungnam', '충남'), ('jeonnam', '전남'), ('Gyeongbuk', '경북'), ('Gyeongnam', '경남'), ('Gangwon', '강원도'), ('jeonbuk', '전북')], default='SEOUL', help_text='주요 지역(시/도)을 선택하세요.', max_length=20),
        ),
        migrations.AlterField(
            model_name='festival',
            name='start_date',
            field=models.DateField(help_text='축제 시작 날짜를 선택하세요. (예: 2025-05-10)'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='데이터가 마지막으로 수정된 일시(자동 입력).'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='website_url',
            field=models.URLField(blank=True, help_text='축제 공식 웹사이트 주소를 입력하세요. (선택사항)', null=True),
        ),
        migrations.AlterField(
            model_name='festivalimage',
            name='festival',
            field=models.ForeignKey(help_text='이미지가 소속된 축제를 선택하세요.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='festivals.festival'),
        ),
        migrations.AlterField(
            model_name='festivalimage',
            name='image',
            field=models.ImageField(help_text='축제 대표 이미지를 업로드하세요.', upload_to='festivals/images/'),
        ),
        migrations.AlterField(
            model_name='festivalimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='이미지가 업로드된 일시(자동 입력).'),
        ),
        migrations.AlterField(
            model_name='regioninterest',
            name='count',
            field=models.PositiveIntegerField(default=0, help_text='지역별 상세페이지 방문 누적 횟수.'),
        ),
        migrations.AlterField(
            model_name='regioninterest',
            name='region',
            field=models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('JEJU', '제주'), ('INCHEON', '인천'), ('GWANGJU', '광주'), ('Daegu', '대구'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기도'), ('Chungbuk', '충북'), ('Chungnam', '충남'), ('jeonnam', '전남'), ('Gyeongbuk', '경북'), ('Gyeongnam', '경남'), ('Gangwon', '강원도'), ('jeonbuk', '전북')], help_text='지역(시/도)을 선택하세요. (중복 불가)', max_length=20, unique=True),
        ),
    ]
