# Generated by Django 5.2.1 on 2025-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='전화번호 숫자만 입력 (예: 0212345678, 01012345678)', max_length=12),
        ),
        migrations.AddField(
            model_name='festival',
            name='fee',
            field=models.PositiveIntegerField(default=0, help_text='참가 요금(원), 0은 무료'),
        ),
        migrations.AddField(
            model_name='festival',
            name='organizer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
