# Generated by Django 5.2.1 on 2025-07-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_alter_festival_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalimage',
            name='image',
            field=models.ImageField(help_text='축제 대표 이미지를 업로드하세요. (최대 2MB, 2~8장)', upload_to='festivals/images/'),
        ),
    ]
