# Generated by Django 5.2.1 on 2025-06-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_festival_contact_phone_festival_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='festivals/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='festivals.festival')),
            ],
        ),
    ]
