# Generated by Django 5.2.1 on 2025-06-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_festivalimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='main_image',
        ),
    ]
