# Generated by Django 5.2.1 on 2025-07-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_alter_festivalimage_image'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='축제와 관련된 태그를 여러 개 선택하세요.', related_name='festivals', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='region',
            field=models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('JEJU', '제주'), ('INCHEON', '인천'), ('GWANGJU', '광주'), ('Daegu', '대구'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기'), ('Chungbuk', '충북'), ('Chungnam', '충남'), ('jeonnam', '전남'), ('Gyeongbuk', '경북'), ('Gyeongnam', '경남'), ('Gangwon', '강원'), ('jeonbuk', '전북')], default='SEOUL', help_text='주요 지역(시/도)을 선택하세요.', max_length=20),
        ),
        migrations.AlterField(
            model_name='regioninterest',
            name='region',
            field=models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('JEJU', '제주'), ('INCHEON', '인천'), ('GWANGJU', '광주'), ('Daegu', '대구'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기'), ('Chungbuk', '충북'), ('Chungnam', '충남'), ('jeonnam', '전남'), ('Gyeongbuk', '경북'), ('Gyeongnam', '경남'), ('Gangwon', '강원'), ('jeonbuk', '전북')], help_text='지역(시/도)을 선택하세요. (중복 불가)', max_length=20, unique=True),
        ),
    ]
