# Generated by Django 5.2.1 on 2025-06-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0004_remove_festival_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('JEJU', '제주'), ('INCHEON', '인천'), ('GWANGJU', '광주'), ('Daegu', '대구'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기도'), ('Chungcheongbuk', '충청북도'), ('Chungcheongnam', '충청남도'), ('jeonnam', '전라남도'), ('Gyeongsangbuk', '경상북도'), ('Gyeongsangnam', '경상남도'), ('Gangwon', '강원도'), ('jeonbuk', '전북')], max_length=20, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='festival',
            old_name='location',
            new_name='detail_region',
        ),
        migrations.AddField(
            model_name='festival',
            name='region',
            field=models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('JEJU', '제주'), ('INCHEON', '인천'), ('GWANGJU', '광주'), ('Daegu', '대구'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기도'), ('Chungcheongbuk', '충청북도'), ('Chungcheongnam', '충청남도'), ('jeonnam', '전라남도'), ('Gyeongsangbuk', '경상북도'), ('Gyeongsangnam', '경상남도'), ('Gangwon', '강원도'), ('jeonbuk', '전북')], default='SEOUL', max_length=20),
        ),
    ]
