# Generated by Django 5.2.1 on 2025-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0004_festival_tags_alter_festival_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='fee',
            field=models.CharField(default=0, help_text='참가 요금을 원 단위로 입력하세요. (무료이면 0 입력)', max_length=70),
        ),
    ]
