# Generated by Django 5.2.1 on 2025-06-27 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0005_regioninterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='latitude',
            field=models.FloatField(blank=True, help_text='축제 개최 장소의 위도', null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='longitude',
            field=models.FloatField(blank=True, help_text='축제 개최 장소의 경도', null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='연락처 숫자만 입력 (예: 0212345678)', max_length=12),
        ),
        migrations.AlterField(
            model_name='festival',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='등록 일시 (자동 생성)'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='description',
            field=models.TextField(help_text='축제 상세 설명 입력'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='detail_region',
            field=models.CharField(help_text='개최 장소 전체 주소 입력', max_length=100),
        ),
        migrations.AlterField(
            model_name='festival',
            name='end_date',
            field=models.DateField(help_text='축제 종료 날짜 (예: 2025-05-12)'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='fee',
            field=models.PositiveIntegerField(default=0, help_text='참가 요금(원) 입력, 무료면 0'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(help_text='축제 공식 명칭 입력 (예: 서울불꽃축제)', max_length=100),
        ),
        migrations.AlterField(
            model_name='festival',
            name='organizer',
            field=models.CharField(blank=True, help_text='주최 기관/부서 입력', max_length=100),
        ),
        migrations.AlterField(
            model_name='festival',
            name='region',
            field=models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('JEJU', '제주'), ('INCHEON', '인천'), ('GWANGJU', '광주'), ('Daegu', '대구'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기도'), ('Chungcheongbuk', '충청북도'), ('Chungcheongnam', '충청남도'), ('jeonnam', '전라남도'), ('Gyeongsangbuk', '경상북도'), ('Gyeongsangnam', '경상남도'), ('Gangwon', '강원도'), ('jeonbuk', '전북')], default='SEOUL', help_text='주요 지역(시/도) 선택', max_length=20),
        ),
        migrations.AlterField(
            model_name='festival',
            name='start_date',
            field=models.DateField(help_text='축제 시작 날짜 (예: 2025-05-10)'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시 (자동 갱신)'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='website_url',
            field=models.URLField(blank=True, help_text='공식 웹사이트 주소 입력', null=True),
        ),
        migrations.AlterField(
            model_name='festivalimage',
            name='festival',
            field=models.ForeignKey(help_text='이미지 소속 축제 선택', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='festivals.festival'),
        ),
        migrations.AlterField(
            model_name='festivalimage',
            name='image',
            field=models.ImageField(help_text='축제 이미지 업로드', upload_to='festivals/images/'),
        ),
        migrations.AlterField(
            model_name='festivalimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='이미지 업로드 일시'),
        ),
        migrations.AlterField(
            model_name='regioninterest',
            name='count',
            field=models.PositiveIntegerField(default=0, help_text='지역별 상세페이지 방문수'),
        ),
        migrations.AlterField(
            model_name='regioninterest',
            name='region',
            field=models.CharField(choices=[('SEOUL', '서울'), ('BUSAN', '부산'), ('JEJU', '제주'), ('INCHEON', '인천'), ('GWANGJU', '광주'), ('Daegu', '대구'), ('Daejeon', '대전'), ('Ulsan', '울산'), ('Sejong', '세종'), ('Gyeonggi', '경기도'), ('Chungcheongbuk', '충청북도'), ('Chungcheongnam', '충청남도'), ('jeonnam', '전라남도'), ('Gyeongsangbuk', '경상북도'), ('Gyeongsangnam', '경상남도'), ('Gangwon', '강원도'), ('jeonbuk', '전북')], help_text='지역(시/도) 선택', max_length=20, unique=True),
        ),
    ]
