# Generated by Django 5.2.1 on 2025-07-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0005_alter_festival_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='visitor_count',
            field=models.PositiveIntegerField(default=0, help_text='축제 방문객 수(명)'),
        ),
    ]
