# Generated by Django 5.2.1 on 2025-07-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0006_festival_visitor_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='website_url',
            field=models.URLField(blank=True, help_text='축제 공식 웹사이트 주소를 입력하세요. (선택사항)', max_length=300, null=True),
        ),
    ]
