# Generated by Django 5.2.1 on 2025-07-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0007_alter_festival_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='region',
            field=models.CharField(choices=[('Seoul', 'Seoul'), ('Busan', 'Busan'), ('Jeju', 'Jeju'), ('Incheon', 'Incheon'), ('Gwangju', 'Gwangju'), ('Daegu', 'Daegu'), ('Daejeon', 'Daejeon'), ('Ulsan', 'Ulsan'), ('Sejong', 'Sejong'), ('Gyeonggi', 'Gyeonggi'), ('Chungbuk', 'Chungbuk'), ('Chungnam', 'Chungnam'), ('Jeonnam', 'Jeonnam'), ('Gyeongbuk', 'Gyeongbuk'), ('Gyeongnam', 'Gyeongnam'), ('Gangwon', 'Gangwon'), ('Jeonbuk', 'Jeonbuk')], default='SEOUL', help_text='주요 지역(시/도)을 선택하세요.', max_length=20),
        ),
        migrations.AlterField(
            model_name='regioninterest',
            name='region',
            field=models.CharField(choices=[('Seoul', 'Seoul'), ('Busan', 'Busan'), ('Jeju', 'Jeju'), ('Incheon', 'Incheon'), ('Gwangju', 'Gwangju'), ('Daegu', 'Daegu'), ('Daejeon', 'Daejeon'), ('Ulsan', 'Ulsan'), ('Sejong', 'Sejong'), ('Gyeonggi', 'Gyeonggi'), ('Chungbuk', 'Chungbuk'), ('Chungnam', 'Chungnam'), ('Jeonnam', 'Jeonnam'), ('Gyeongbuk', 'Gyeongbuk'), ('Gyeongnam', 'Gyeongnam'), ('Gangwon', 'Gangwon'), ('Jeonbuk', 'Jeonbuk')], help_text='지역(시/도)을 선택하세요. (중복 불가)', max_length=20, unique=True),
        ),
    ]
